//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employeeID { get; set; }
        public Nullable<int> employeeSalary { get; set; }
        public string employeeName { get; set; }
        public string employeeDetails { get; set; }
        public string employeeRole { get; set; }
    }
}
